pipeline {
  agent none
  stages {
	stage('Cloning Git') {
      steps {
        git 'https://github.com/bhavanap90/DockerBuildRepo.git'
      }
    }
    stage('Docker Build') {
      agent any
      steps {
        sh 'docker build -t bhavanaprabhu/testrepo:FirstProject_v1 .'
      }
    }
    stage('Docker Push') {
      agent any
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
          sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
          sh 'docker push bhavanaprabhu/testrepo:FirstProject_v1'
        }
      }
    }
	stage('Docker Run') {
      agent any
      steps {
        sh 'docker run bhavanaprabhu/testrepo:FirstProject_v1'
      }
    }
  }
}